name: church_navigation
description: 외국인을 위한 교회 도움 앱입니다. 
publish_to: 'none' 
version: 1.0.0+1 
environment:
  sdk: '>=3.7.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.3
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  dio: ^5.4.2
  retrofit: ^4.2.0
  json_annotation: ^4.9.0
  flutter_secure_storage: ^8.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  mysql1: ^0.19.2 
  http: ^0.13.3
  flutter_riverpod: ^2.5.1
  cached_network_image: ^3.1.0
  flutter_typeahead: ^3.1.0
  photo_view: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^9.1.9

flutter:
  uses-material-design: true
